version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=eco_db
      - POSTGRES_USER=${LOGIN}
      - POSTGRES_PASSWORD=${PASSWORD}
    ports:
      - '5432:5432'
    networks:
      - eco-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${LOGIN} -d eco_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecoapp-container
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/eco_db
      - SPRING_DATASOURCE_USERNAME=${LOGIN}
      - SPRING_DATASOURCE_PASSWORD=${PASSWORD}
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    ports:
      - '8080:8080'
    networks:
      - eco-network

networks:
  eco-network:
    driver: bridge

volumes:
  postgres-data:
